version: "3.9"

x-common-variables: &common-variables
    DB_HOST: "10.10.12.2"
    DB_PORT: "3306"
    MYSQL_ROOT_PASSWORD: "pass"
    MYSQL_USER: "root"
    MYSQL_PASS: "pass"
    DB_NAME: "ProyectoDocker"

services:
  frontend:
    build: ./app
    ports:
      - "80:80"
    networks:
      - project_network
    depends_on:
      - load_balancer

  api:
    build: ./api
    environment:
      <<: *common-variables
    networks:
      - project_network
    depends_on:
      - database

  database:
    image: mysql:latest
    restart: always
    environment: *common-variables
    volumes:
      - datavolume:/var/lib/mysql
      - ./database/database-script.sql:/docker-entrypoint-initdb.d/database-script.sql
    networks:
      project_network:
        ipv4_address: 10.10.12.2

volumes:
  datavolume:

networks:
  project_network:
    driver: bridge
    ipam:
      config:
        - subnet: "10.10.12.0/24"
