version: "3.9"

x-common-variables: &common-variables
    DB_HOST: "10.10.12.2"
    DB_PORT: "3306"
    MYSQL_ROOT_PASSWORD: "pass"
    DB_NAME: "ProyectoDocker"


services:
    database:
      image: mysql:8.0.29-oracle
      restart: always
      environment: *common-variables
      ports:
      - "3306:3306"
      volumes:
        - datavolume:/var/lib/mysql
        - ./database-script.sql:/docker-entrypoint-initdb.d/database-script.sql
    
    redis:
      image: "bitnami/redis:6.0.16"
      restart: always
      ports:
          - 6379:6379
      environment: 
          - ALLOW_EMPTY_PASSWORD=yes

volumes:
  datavolume:
